language: node_js
sudo: required
dist: trusty
node_js:
  - "node"
addons:
  postgresql: "10"
services:
  - postgresql
script: "npm test"
before_script:
  - node app.js
  - psql -c 'CREATE DATABASE fkdb;' -U postgres
# env:
# - DATABASE_URL=postgres://postgres@localhost:5432/